Feat: Initial code import
Import action code from the
lfit/releng-reusable-workflows repository.
Missing action documentation has been created.

Co-authored-by: Claude <noreply@anthropic.com>
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,37 +1,158 @@
 ---
 # SPDX-License-Identifier: Apache-2.0
-# SPDX-FileCopyrightText: 2025 The Linux Foundation
+# SPDX-FileCopyrightText: 2024 The Linux Foundation
 
-# actions-template
-name: "🛠️ Actions Template"
-description: "Description of action"
-# Any relevant notes/observations can go here
+# github-list-releases-action
+name: "📦 List GitHub Releases"
+description: "Returns a list of releases for the current repository"
+# Limited to 1000 records due to GitHub API query limits
+# 640K ought to be enough for anybody
+# ToDo: investigate support for API query pagination
 
 inputs:
-  input:
-    description: "Description of input"
-    required: true
+  # Optional
+  TAG:
+    description: "Check if this tag/version has been released"
+    required: false
+  SUMMARY_OUTPUT:
+    description: "Displays summary output"
+    required: false
+    default: "false"
+  PRODUCTION_ONLY:
+    description: "Pre-release and draft releases are included"
+    required: false
+    default: "false"
+  RETURN_TYPE:
+    description: "Set to either: text|json"
+    required: false
+    default: "text"
+  JSON_FIELDS:
+    # Mandatory when return type (above) is set to JSON
+    description: "Fields to return when return type set to JSON"
+    required: false
+    default: "tagName"
+  ORDER:
+    description: "Sort order: asc|desc"
+    required: false
+    default: "desc"
 
 outputs:
-  output:
-    description: "Description of output"
-    value: ${{ steps.code.outputs.output }}
+  # Mandatory
+  RELEASES:
+    description: "List of releases in specified output format"
+    value: ${{ steps.releases.outputs.releases }}
+  # Optional
+  RELEASED:
+    description: "Has provided tag/version already been released"
+    value: ${{ steps.releases.outputs.tag }}
 
 runs:
   using: "composite"
   steps:
-    - name: "Friendly Name"
-      id: code
+    - name: "List GitHub Releases"
+      id: releases
       shell: bash
       run: |
-        # Friendly Name
-        input="${{ inputs.input }}"
-        if [ -z "$input" ]; then
-          echo "Error: mandatory input was not set/configured ❌"
+        # List GitHub Releases
+
+        # Check GitHub CLI is available
+        GH_CLI=$(which gh)
+        if [ ! -x "$GH_CLI" ]; then
+          echo "Error: GitHub CLI was NOT found in PATH ❌"
           exit 1
         fi
 
-        echo "output=$input" >> "$GITHUB_ENV"
-        echo "output=$input" >> "$GITHUB_OUTPUT"
-        echo "Action received: $input ✅"
-        echo "Action received: $input ✅" >> "$GITHUB_STEP_SUMMARY"
+        # Function to check releases
+        checkReleases() {
+          while IFS= read -r RELEASE ; do
+          if [ "$RELEASE" = "$TAG" ]; then
+            RELEASED="true"
+          fi
+          done <<< "$RELEASES"
+        }
+
+        # Case-insensitive matching of inputs
+        SUMMARY_OUTPUT=$(echo ${{ inputs.summary_output }} |\
+          tr '[:upper:]' '[:lower:]')
+        PRODUCTION_ONLY=$(echo ${{ inputs.PRODUCTION_ONLY }} |\
+          tr '[:upper:]' '[:lower:]')
+        RETURN_TYPE=$(echo ${{ inputs.return_type }} |\
+          tr '[:upper:]' '[:lower:]')
+        ORDER=$(echo ${{ inputs.order }} |\
+          tr '[:upper:]' '[:lower:]')
+        TAG="${{ inputs.tag }}"
+
+        # Set baseline flags for the CLI command
+        # Note: limit MUST be provided numerically to GH CLI
+        CLI_FLAGS="release list  --limit 1000 -O \
+          ${{ inputs.ORDER }} --limit 1000"
+
+        if [ "f$PRODUCTION_ONLY" = "ffalse" ]; then
+          CLI_FLAGS="$CLI_FLAGS --exclude-drafts --exclude-pre-releases"
+        fi
+
+        # Check dependent input parameters are coherent
+        if [ "$RETURN_TYPE" = "json" ] && [ -z "$JSON_FIELDS" ]; then
+          echo "Error: fields MUST be specified when return type is JSON ❌"
+          exit 1
+        elif [ "$RETURN_TYPE" = "json" ]; then
+          CLI_FLAGS="$CLI_FLAGS --json ${{ inputs.JSON_FIELDS }}"
+        fi
+
+        echo "Fetching GitHub Releases 📦"
+        if [ "f$SUMMARY_OUTPUT" = "ftrue" ]; then
+          echo "### 📦 GitHub List Releases" >> "$GITHUB_STEP_SUMMARY"
+        fi
+
+        # Run and capture GitHub CLI Command
+        if [ "$RETURN_TYPE" = "text" ]; then
+          # Text output is actually a JSON query processed with fixed arguments
+          echo "Running: $GH_CLI $CLI_FLAGS"
+          RELEASES=$($GH_CLI $CLI_FLAGS --json tagName -q '.[] | .tagName')
+        else
+          echo "Running: $GH_CLI $CLI_FLAGS"
+          RELEASES=$($GH_CLI $CLI_FLAGS)
+        fi
+
+        # Only list releases if/when values are returned
+        if [ -n "$RELEASES" ]; then
+          echo "Releases in this repository:"
+          echo "$RELEASES"
+        fi
+
+        if [ -z "$TAG" ]; then
+          # Exit early if no tag/version to check in releases
+          exit 0
+        fi
+
+        # Check with leading character in place
+        echo "Checking for: $TAG"
+        checkReleases
+
+        if [ "$RELEASED" != "true" ]; then
+          if [[ "$TAG" == v* ]]; then
+            TAG="${TAG:1}"
+            # Check again with leading 'v' character stripped
+            echo "Checking for: $TAG"
+            checkReleases
+          fi
+        fi
+
+        # Set output value
+        echo "RELEASED=$RELEASED" >> "$GITHUB_ENV"
+        echo "RELEASED=$RELEASED" >> "$GITHUB_OUTPUT"
+
+        if [ "$RELEASED" = "true" ]; then
+          echo "${{ inputs.tag }} HAS already been release ⚠️"
+        else
+          echo "${{ inputs.tag }} has not previously been released ✅"
+        fi
+        if [ "f$SUMMARY_OUTPUT" = "ftrue" ]; then
+          if [ "$RELEASED" = "true" ]; then
+            echo "Release already published: $TAG ⚠️" \
+              >> "$GITHUB_STEP_SUMMARY"
+          else
+            echo "Release not published yet: $TAG ✅" \
+              >> "$GITHUB_STEP_SUMMARY"
+          fi
+        fi
